#deployment.yaml
replicaCount: 3
image:
  repository: httpd
  tag: latest
containerPort: 80



# service.yaml
service:
  port: 80
  targetPort: 80
  nodePort: 30000
  type: NodePort


 
